services:
  mediawiki:
    image: docker-registry.wikimedia.org/dev/bookworm-php83-fpm:1.0.0
    user: "${MW_DOCKER_UID}:${MW_DOCKER_GID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./core:${MW_INSTALL_PATH}:cached"
      - "./config:/srv/mediawiki-config:cached"
      - "./extensions:${MW_INSTALL_PATH}/extensions"
      - "./skins:${MW_INSTALL_PATH}/skins"
    env_file: config/.env
    networks: [ mw ]
  mediawiki-web:
    image: docker-registry.wikimedia.org/dev/bookworm-apache2:1.0.1
    user: "${MW_DOCKER_UID}:${MW_DOCKER_GID}"
    ports:
      - "${MW_DOCKER_PORT:-8080}:8080"
    volumes:
      - "./core:${MW_INSTALL_PATH}:cached"
      - "./config:/srv/mediawiki-config:cached"
      - "./extensions:${MW_INSTALL_PATH}/extensions"
      - "./skins:${MW_INSTALL_PATH}/skins"
    env_file: config/.env
    networks: [ mw ]
  mediawiki-jobrunner:
    image: docker-registry.wikimedia.org/dev/bookworm-php83-jobrunner:1.0.0
    user: "${MW_DOCKER_UID}:${MW_DOCKER_GID}"
    volumes:
      - "./core:${MW_INSTALL_PATH}:cached"
      - "./config:/srv/mediawiki-config:cached"
      - "./extensions:${MW_INSTALL_PATH}/extensions"
      - "./skins:${MW_INSTALL_PATH}/skins"
    env_file: config/.env
    networks: [ mw ]
  elasticsearch:
    image: docker-registry.wikimedia.org/repos/search-platform/cirrussearch-elasticsearch-image:v7.10.2-5
    # on an Apple M1 / arm64 system, you can use kostajh/wmf-elasticsearch-arm64:7.10.2,
    # see https://gitlab.wikimedia.org/kharlan/wmf-elasticsearch-arm64/
    # image: docker.io/kostajh/wmf-elasticsearch-arm64:7.10.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    networks: [ mw ]
    ports:
      - "${ELASTICSEARCH_HTTP_PORT:-9200}:9200"
      - "${ELASTICSEARCH_TCP_PORT:-9300}:9300"
    profiles: [ "elasticsearch" ]
  mariadb:
    image: mariadb:latest
    volumes:
      - mariadbdata:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MWC_DB_ROOT_PASSWORD}
      - MARIADB_USER=${MWC_DB_USER}
      - MARIADB_PASSWORD=${MWC_DB_PASSWORD}
      - MARIADB_DATABASE=${MWC_DB_DATABASE}
    networks: [ mw ]
    ports: [ "${MARIADB_PORT:-3306}:3306" ]
    profiles: [ "mariadb" ]
  mysql:
    image: mysql:latest
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MWC_DB_ROOT_PASSWORD}
      - MYSQL_USER=${MWC_DB_USER}
      - MYSQL_PASSWORD=${MWC_DB_PASSWORD}
      - MYSQL_DATABASE=${MWC_DB_DATABASE}
    networks:
      - mw
    ports: [ "${MYSQL_PORT:-3307}:3306" ]
    profiles: [ "mysql" ]
  function-orchestrator:
    image: docker-registry.wikimedia.org/repos/abstract-wiki/wikifunctions/function-orchestrator:latest
    # Un-comment this if you're using a local build, by running this in your check-out of the orchestrator:
    # docker build -f .pipeline/blubber.yaml --target development -t local-orchestrator .
    # image: local-orchestrator:latest
    networks: [ mw ]
    profiles: [ "wikifunctions" ]
    #ports:
    #  - 6254:6254
    environment:
      WIKI_API_URL: "http://${COMPOSE_PROJECT_NAME}-mediawiki-web-1:8080/w/api.php"
      WIKIDATA_API_URL: "https://www.wikidata.org"
      ORCHESTRATOR_CONFIG: |
        {
          "evaluatorConfigs": [
            {
              "programmingLanguages": [
                "Z610",
                "Z611",
                "Z612",
                "Z613",
                "Z614",
                "Z615"
              ],
              "evaluatorUri": "http://${COMPOSE_PROJECT_NAME}-function-evaluator-python-1:6927/1/v1/evaluate/",
              "evaluatorWs": "",
              "useReentrance": false
            },
            {
              "programmingLanguages": [
                "Z600",
                "Z601",
                "Z602",
                "Z603",
                "Z604",
                "Z605",
                "Z606",
                "Z607",
                "Z608"
              ],
              "evaluatorUri": "http://${COMPOSE_PROJECT_NAME}-function-evaluator-javascript-1:6927/1/v1/evaluate/",
              "evaluatorWs": "",
              "useReentrance": false
            }
          ]
        }
  function-evaluator-javascript:
    image: docker-registry.wikimedia.org/repos/abstract-wiki/wikifunctions/function-evaluator/wasm-javascript-all:latest
    # Un-comment this if you're using a local build, by running this in your check-out of the evaluator:
    # docker build -f .pipeline/blubber.yaml --target development-javascript-all-wasm -t local-evaluator-js .
    # image: local-evaluator-js:latest
    networks: [ mw ]
    profiles: [ "wikifunctions" ]
    #ports:
    #  - 6929:6927
  function-evaluator-python:
    image: docker-registry.wikimedia.org/repos/abstract-wiki/wikifunctions/function-evaluator/wasm-python3-all:latest
    # Un-comment this if you're using a local build, by running this in your check-out of the evaluator:
    # docker build -f .pipeline/blubber.yaml --target development-python3-all-wasm -t local-evaluator-py .
    # image: local-evaluator-py:latest
    networks: [ mw ]
    profiles: [ "wikifunctions" ]
    #ports:
    #  - 6928:6927

volumes:
  esdata:
    driver: local
  mariadbdata:
    driver: local
  mysqldata:
    driver: local

networks:
  mw:
